### ISSUE TITLE
README 错误

### ISSUE THREAD

**Issue by frostime** [2234839/OceanPress_siyuan_plugin#1]
![image](https://github.com/2234839/OceanPress_siyuan_plugin/assets/27268127/2ffb6996-59a6-4e95-b097-a18fd43a08d8)

请检查一下你的 README_zh-CN.md ，模板的 readme 忘了删掉了。

![image](https://github.com/2234839/OceanPress_siyuan_plugin/assets/27268127/36709970-45c6-4ba2-8d7a-3ad829af7b01)

**Comment by 2234839** [comment]
好的，感谢反馈
