### ISSUE TITLE
关闭插件会造成图片丢失

### ISSUE THREAD

**Issue by pisceswb** [2234839/OceanPress_siyuan_plugin#4]
发现一个可怕的bug，关闭插件会造成当前页图片全部丢失，请作者修复，谢谢！

**Comment by 2234839** [comment]
感谢反馈

**Comment by 2234839** [comment]
更新到 0.3.17 即可

**Comment by pisceswb** [comment]
谢谢。请问能否修复一下这个issue：
https://github.com/2234839/OceanPress_siyuan_plugin/issues/6
