### ISSUE TITLE
启用插件后，点击图片不能选中图片了

### ISSUE THREAD

**Issue by pisceswb** [2234839/OceanPress_siyuan_plugin#6]
启用插件后，点击图片不能选中图片了。
未启用插件时，点击图片能够选中，可以使用Ctrl C复制图片；启用插件后，点击图片不能选中图片了。希望大佬修复

**Comment by 2234839** [comment]
依旧十分感谢反馈，更新到 0.3.19 即可

**Comment by pisceswb** [comment]
👍👍大佬给力！！
