### ISSUE TITLE
图片完成umi ocr识别后的边框，能否不把图片标题一起框起来？

### ISSUE THREAD

**Issue by pisceswb** [2234839/OceanPress_siyuan_plugin#9]
边框只框住图片，不框住图片标题，更美观一些。
如果不好加框线的话，可以使用下面给图片加阴影的方法。

.b3-typography img, .protyle-wysiwyg img {
	box-shadow: 0 0 3px green;
}

![image](https://github.com/2234839/OceanPress_siyuan_plugin/assets/104658457/3d724381-c626-4667-a23e-c0b2d1da6958)

**Comment by 2234839** [comment]
感谢反馈，我等会改改

**Comment by pisceswb** [comment]
.b3-typography img, .protyle-wysiwyg img {
box-shadow: 0 0 3px gray;
}

灰色边框好看。
识别失败的图片，能否也加上灰色边框，这样批量umi ocr识别完成后，所有图片都有灰色边框了。
我可以把我原来的灰色边框自定义css取消，使用这个插件加灰色边框了 😁

**Comment by 2234839** [comment]
可以的，很好的建议

**Comment by 2234839** [comment]
更新到 0.3.21 即可，另外失败采用灰色边框有些过于不明显了，我改成了红色

**Comment by pisceswb** [comment]
> 更新到 0.3.21 即可，另外失败采用灰色边框有些过于不明显了，我改成了红色

有些图片，本就是普通照片，可能没有文字，还很大，可能导致识别失败。并不是因为错误或其它技术原因导致识别失败的。
您不用太在意“识别失败”，认为这是一个值得注意的一个的问题，因为没有成功识别的图片，就是应该是失败的。
感觉没必要特别标记。

**Comment by pisceswb** [comment]
umi ocr软件还是很好用的，识别失败是图片的问题，不是umi ocr的问题。

**Comment by 2234839** [comment]
有道理，改成灰色了

**Comment by pisceswb** [comment]
> 如果使用批量ocr识别功能的话，需要关闭再重新打开标签页，才能使已经打开的标签页中的图片边框颜色更改。
@2234839

**Comment by 2234839** [comment]
切换一下标签页应该也可以，这是为了节约性能，只有图片重新加载的时候才会再次进行检测

**Comment by 2234839** [comment]
这个时间是一秒,因为插件每隔一秒会进行一次检测，间隔太短性能消耗比较大

**Comment by pisceswb** [comment]
> 这个时间是一秒,因为插件每隔一秒会进行一次检测，间隔太短性能消耗比较大

请问能把图片添加边框设置成一个可选项吗？或给出修改插件代码以开启或关闭该功能也行。不想要这个延迟和每隔1s的检测。部分用户也可能不想给图片加上边框，毕竟大部分用户都是用的默认的没有边框的

**Comment by 2234839** [comment]
边框可以加选项，检测是不可少的

**Comment by pisceswb** [comment]
> 边框可以加选项，检测是不可少的

也就是不启用边框的情况下，ocr批量进行完了，该插件还会每隔1s检测一次吗？没必要检测了呀？

**Comment by 2234839** [comment]
得检测有没有图片加载出来，有图片加载了插件需要给他覆盖文本层在上面

**Comment by pisceswb** [comment]
> 得检测有没有图片加载出来，有图片加载了插件需要给他覆盖文本层在上面

明白了，谢谢解惑。
后面也可以设计成，不对文档中的图片进行文本层覆盖，只对双击打开后的图片进行文本层覆盖，是不是就不用每秒检测1次了。

**Comment by 2234839** [comment]
是的

**Comment by 2234839** [comment]
这个每秒一次的扫描新增图片其实性能消耗很少，但如果要扫描变化，也就是之前你说的识别成功了自动更新边框，就会消耗很多性能，这涉及到了磁盘io和思源内核交互

**Comment by pisceswb** [comment]
那还是不想加边框了，不想为了美观损失太多性能。
期待您有时间时，可以实现能够选择不加边框，不每秒扫描，只对打开的大图进行文本层覆盖的更新。@2234839

**Comment by pisceswb** [comment]
> 这个每秒一次的扫描新增图片其实性能消耗很少，但如果要扫描变化，也就是之前你说的识别成功了自动更新边框，就会消耗很多性能，这涉及到了磁盘io和思源内核交互

我理解成扫描新增图片，增加文字涂层，性能消耗小；自动更新边框，性能消耗大了

**Comment by 2234839** [comment]
你理解的也没错，可能我对于更新边框的描述不够清楚，边框从无到有消耗的性能是很少的，但实时变化边框（例如插件的ocr结果被删除了、用户又执行了一次ocr,之前失败，这次成功了）在这种情况下而且页面无刷新的话，插件要想监测到并自动更新会很消耗性能

**Comment by pisceswb** [comment]
> 你理解的也没错，可能我对于更新边框的描述不够清楚，边框从无到有消耗的性能是很少的，但实时变化边框（例如插件的ocr结果被删除了、用户又执行了一次ocr,之前失败，这次成功了）在这种情况下而且页面无刷新的话，插件要想监测到并自动更新会很消耗性能

👍 感谢解惑，期待更新
